## Â© 2022 Nephio Authors
## Licensed under the Apache License 2.0
## SPDX-License-Identifier: Apache-2.0
---
- name: Slurp access token
  ansible.builtin.slurp:
    src: /home/{{ cloud_user }}/gitea/nephio-gitea-token
  register: gitea_token
  when:
    - gitea_username is defined
- name: Delete repos
  ansible.builtin.uri:
    url: http://localhost:3000/api/v1/repos/nephio/nephio-{{ item.key }}
    headers:
      Authorization: token {{ gitea_token['content'] | b64decode }}
      accept: application/json
    method: DELETE
    status_code: 204
    body_format: json
  register: result
  with_dict: "{{ clusters }}"
  when:
    - gitea_username is defined
- name: Print return information from the previous task
  ansible.builtin.debug:
    var: result
    verbosity: 2
  when:
    - gitea_username is defined
