- hosts: vm
  environment:
    http_proxy: "{{proxy.http_proxy}}"
    https_proxy: "{{proxy.https_proxy}}"
    no_proxy: "{{proxy.no_proxy}}"
  roles:
    
    - { role: docker, tags: docker}
    - { role: kubectl, tags: kubectl}
    - { role: kind, tags: kind}
    - { role: kpt, tags: kpt}
    - { role: cni, tags: cni }
    - { role: bash, tags: bash }
    - { role: tree, tags: tree}
    - { role: nephio/install, tags: nephio}
    - { role: clab, tags: clab}