## Â© 2022 Nokia
## Licensed under the Apache License 2.0
## SPDX-License-Identifier: Apache-2.0
---
- name: Download the {{ item.package }} packages, with url {{ nephio.packages_url }}/{{ item.package }}
  shell: kpt pkg get --for-deployment {{ nephio.packages_url }}/{{ item.package }}
  args: 
    chdir: "{{ tmp_directory }}/{{ nephio.install_dir}}"
  register: result
  failed_when:
    - result.rc > 1
    - result.rc == 1 and "already exists" not in result.stderr

- name: Initialize {{ item.package }}
  shell: kpt fn render {{ item.package }}
  args: 
    chdir: "{{ tmp_directory }}/{{ nephio.install_dir}}"