## Â© 2022 Nokia
## Licensed under the Apache License 2.0
## SPDX-License-Identifier: Apache-2.0

---

- name: adding alias in ~/.bashrc
  lineinfile: 
    path: ~/.bashrc 
    line: "alias k=kubectl"

- name: adding alias in ~/.bashrc
  lineinfile: 
    path: ~/.bashrc 
    line: "source <(kubectl completion bash)"

- name: adding alias in ~/.bashrc
  lineinfile: 
    path: ~/.bashrc 
    line: "source <(kpt completion bash)"