## Â© 2022 Nephio Authors
## Licensed under the Apache License 2.0
## SPDX-License-Identifier: Apache-2.0

---
- name: Create tmp cni directory
  ansible.builtin.file:
    path: "{{ tmp_directory }}/cni"
    state: directory
    mode: '0755'

- name: Copy cni binary to tmp_directory
  become: true
  ansible.builtin.copy:
    src: "{{ installer_lib }}/cni-plugins-{{ host_os }}-{{ host_arch }}-v{{ cni_version }}.tgz"
    dest: "{{ tmp_directory }}"
    mode: "0600"
  tags:
    - cni

- name: Unarchive cni archive
  ansible.builtin.unarchive:
    src: "{{ tmp_directory }}/cni-plugins-{{ host_os }}-{{ host_arch }}-v{{ cni_version }}.tgz"
    dest: "{{ tmp_directory }}/cni"
    remote_src: true
  tags:
    - cni
