- name: Slurp access token
  ansible.builtin.slurp:
    src: /home/{{ cloud_user }}/gitea/nephio-gitea-token
  register: gitea_token
  when:
    - gitea_username is defined
- name: Create repos
  ansible.builtin.uri:
    url: http://localhost:3000/api/v1/user/repos
    headers:
      Authorization: token {{ gitea_token['content'] | b64decode }}
      Content-Type: application/json
      accept: application/json
    method: POST
    body: {'auto_init': true, 'name': "nephio-{{ item.key }}"}
    status_code: 201
    body_format: json
  register: result
  with_dict: "{{ clusters }}"
  when:
    - gitea_username is defined
- name: Print return information from the previous task
  ansible.builtin.debug:
    var: result
    verbosity: 2
  when:
    - gitea_username is defined
