## Â© 2022 Nephio Authors
## Licensed under the Apache License 2.0
## SPDX-License-Identifier: Apache-2.0

---
- name: github url
  set_fact:
    github_url: "{{ 'https://api.github.com/repos/{{ github_organization }}' if (github_organization is defined and github_organization != '') else 'https://api.github.com/repos/{{ github_username }}' }}"
  when:
    - github_username is defined

- name: delete repo nephio-{{ item.key }}
  ansible.builtin.uri:
    url: "{{ github_url}}/nephio-{{ item.key }}"
    headers:
      Accept: application/vnd.github+json
      Authorization: Bearer {{ github_token }}
      X-GitHub-Api-Version: 2022-11-28
    method: DELETE
    status_code: 204
    body_format: json
  register: result
  with_dict: "{{ clusters }}"
  when:
    - item.key != "mgmt"

- name: delete repo nephio-catalog
  ansible.builtin.uri:
    url: "{{ github_url}}/nephio-catalog"
    headers:
      Accept: application/vnd.github+json
      Authorization: Bearer {{ github_token }}
      X-GitHub-Api-Version: 2022-11-28
    method: DELETE
    status_code: 204
    body_format: json
  register: result
  with_dict: "{{ clusters }}"
  when:
    - item.key == "mgmt"
